#!/bin/bash

sudo mkdir -p /opt/portainer
docker service create \
  --name portainer \
  --publish 9000:9000 \
  --replicas=1 \
  --constraint 'node.role == manager' \
  --mount type=bind,src=//var/run/docker.sock,dst=/var/run/docker.sock \
  --mount type=bind,src=//opt/portainer,dst=/data \
  portainer/portainer \
  -H unix:///var/run/docker.sock
